### ISSUE TITLE
Compile error GUI wallet linux 

### ISSUE THREAD

**Issue by devjohn2k** [OlympicCoinTeam/OlympicCoin#1]
OS: Ubuntu 16.04

Compile error: 
make
/bin/sh: 1: ./autogen.sh: not found
Makefile:893: fallo en las instrucciones para el objetivo '/home/olympic/OlympicCoin/src/secp256k1/src/libsecp256k1_la-secp256k1.o'
make: *** [/home/olympic/OlympicCoin/src/secp256k1/src/libsecp256k1_la-secp256k1.o] Error 127

This happens because the secp256k1 folder is empty

Possible fix:
Copy from the old repository the folder secp256k1

**Comment by OlympicCoinTeam** [comment]
Check Guide
https://github.com/OlympicCoinTeam/OlympicCoin/blob/master/guides/MN_GUIDE_HOT_n_COLD.md
